apiVersion: v1
kind: Service
metadata:
  name: hello-test
  labels:
    app: hello-test
    service: hello-test
spec:
  selector:
    app: hello-test-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-test-deployment
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hello-test-deployment
  template:
    metadata:
      labels:
        app: hello-test-deployment
    spec:
      containers:
      - name: hello-test
        image: haozi23333/hello-test:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000