esname: hello-test
manifestType: rawManifest
resourcePath: [ 'manifest/templates' ]

service:
  - name: hello-test-deployment
    serviceType: deployment
    gitUrl: https://github.com/haozi23333/hello-nocaltest.git
    devContainerImage: haozi23333/hello-test:dev
    workDir: /app
    syncDirs:
      - ./
    devPorts:
      - 9090:3000