esname: hello-test
manifestType: rawManifest
resourcePath: [ 'manifest/templates' ]

service:
  - name: hello-test
    serviceType: deployment
    gitUrl: https://github.com/haozi23333/hello-nocaltest.git
    devContainerImage: haozi23333/hello-test
    workDir: /app
    syncDirs:
    - ./
    devPorts:
    - 8080:3000